/* Portable call-boundary contract using actual staged FolderCache functions. */
#define _POSIX_C_SOURCE 200809L
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "foldercache_types.inc"

typedef unsigned long DWORD;
typedef struct FolderNode { int unused; } FolderNode;
typedef struct FolderCache {
    FolderNode *root, *root_tail;
    int critSecAllFiles;
    char **gamedatadirs, **piggs;
    char *test_path;
} FolderCache;
typedef struct { FolderCache *fc; int virtual_location; } DirectoryUpdateContext;

#define true 1
#define DIR_MON_NO_TIMESTAMPS 1
#define eaCreate(address) ((void)(address))
#define verbose_printf(...) ((void)0)
static FolderCacheMode test_mode;
static int watch_calls, flag_calls, scan_calls, hash_calls, poll_calls;
static int count_file, count_folder, folder_cache_debug;

DWORD GetCurrentThreadId(void) { return 42; }
void InitializeCriticalSectionAndSpinCount(int *section, unsigned spin) {
    assert(section && spin == 4000);
}
char *FolderCache_GetFromVirtualLocation(FolderCache *fc, int location) {
    assert(location == 0); return fc->test_path;
}
void FolderCache_SetFromVirtualLocation(FolderCache *fc, int location, char *path) {
    assert(location == 0 && !fc->test_path); fc->test_path = path;
}
FolderCacheMode FolderCacheGetMode(void) { return test_mode; }
void dirMonSetFlags(int flags) { assert(flags == DIR_MON_NO_TIMESTAMPS); flag_calls++; }
int dirMonAddDirectory(const char *path, int recursive, void *data) {
    DirectoryUpdateContext *context = data;
    assert(!strcmp(path, "data") && recursive == 1 && context->virtual_location == 0);
    assert(context->fc && !strcmp(context->fc->test_path, path));
    watch_calls++; free(context); return 1;
}
int timerAlloc(void) { return 7; }
void timerStart(int timer) { assert(timer == 7); }
void timerFree(int timer) { assert(timer == 7); }
double timerElapsed(int timer) { assert(timer == 7); return 0.0; }
void FolderCacheAddFolderToNode(FolderCache *fc, FolderNode **root, FolderNode **tail,
                               FolderNode *parent, const char *path, int location) {
    assert(fc && root == &fc->root && tail == &fc->root_tail && !parent);
    assert(!strcmp(path, "data") && location == 0); scan_calls++;
}
void FolderCacheBuildHashTable(FolderCache *fc, FolderNode *root, const char *prefix) {
    assert(fc && root == fc->root && !*prefix); hash_calls++;
}
void FolderNodeGetCounts(int *discard, int *update) { *discard = *update = 0; }

/* Generated by the Python test directly from the real patched source. */
#include "foldercache_source_fragments.inc"

int main(void)
{
    int fixed, mode;
    for (fixed = 0; fixed <= 1; fixed++) {
        for (mode = FOLDER_CACHE_MODE_DEVELOPMENT; mode <= FOLDER_CACHE_MODE_FILESYSTEM_ONLY; mode++) {
            FolderCache *cache;
            int expected_watch = !fixed && mode != FOLDER_CACHE_MODE_PIGS_ONLY && mode != FOLDER_CACHE_MODE_FILESYSTEM_ONLY;
            int expected_scan = mode == FOLDER_CACHE_MODE_DEVELOPMENT || mode == FOLDER_CACHE_MODE_I_LIKE_PIGS;
            folder_cache_fixed_inputs = 0; folder_cache_update_enable = 1; threadid = 0;
            watch_calls = flag_calls = scan_calls = hash_calls = poll_calls = 0;
            test_mode = (FolderCacheMode)mode;
            if (fixed)
                assert(FolderCacheSetFixedInputsMode() == 1);
            cache = FolderCacheCreate();
            assert(threadid == 42);
            FolderCacheAddFolder(cache, "data", 0);
            assert(test_mode == (FolderCacheMode)mode);
            assert(!strcmp(cache->test_path, "data"));
            assert(watch_calls == expected_watch && flag_calls == expected_watch);
            assert(scan_calls == expected_scan && hash_calls == expected_scan);
            FolderCacheEnableCallbacks(1);
            assert(test_update_entry() == !fixed);
            assert(poll_calls == !fixed);
            /* A caller cannot activate after a cache was created, even if that
             * mode did not itself need a watch. Existing behavior is untouched. */
            assert(FolderCacheSetFixedInputsMode() == 0);
            assert(folder_cache_fixed_inputs == fixed);
            FolderCacheEnableCallbacks(0);
            assert(test_update_entry() == 0);
            free(cache->test_path); free(cache);
        }
    }
    puts("PASS actual FolderCache fixed-input boundary contract");
    return 0;
}
